- hosts: jenkins
  become: true
  vars:
    user_admin_password: "{{ lookup('community.general.env', 'USER_ADMIN_PASSWORD') }}"
    user_user_password: "{{ lookup('community.general.env', 'USER_USER_PASSWORD') }}"

  tasks:
    - name: add jenkins key
      apt_key:  # ansible module to add key
        url:  https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present

    - name: add jenkins repo
      apt_repository: #ansible module to add repo
        repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
        state: present

    - name: install java
      apt:
        name: openjdk-17-jre
        state: present

    - name: install jenkins  #install jenkins
      apt:
        name: jenkins
        state: present

    - name: start jenkins service
      service:
        name: jenkins
        state: started

    - name: enable jenkins to start at boot time
      service:
        name: jenkins
        enabled: yes

    - name: Retrieve initial Jenkins admin password
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_admin_password

    - name: Upload Jenkins Configuration as Code (JCasC) file
      copy:
        src: ../casc/jenkins-casc.yml
        dest: /var/lib/jenkins/jenkins-casc.yaml
        owner: jenkins
        group: jenkins
        mode: '0644'

    - name: Add Jenkins Configuration as Code environment variable
      lineinfile:
        path: /etc/default/jenkins
        line: 'JAVA_ARGS="$JAVA_ARGS -Djenkins.install.runSetupWizard=false -Djenkins.config.file=/var/lib/jenkins/jenkins-casc.yaml"'
        state: present

    - name: Restart Jenkins to apply JCasC
      service:
        name: jenkins
        state: restarted

    - name: Display initial Jenkins admin password
      debug:
        msg: "Initial Jenkins admin password is: {{ jenkins_admin_password.stdout }}"