jenkins:
  systemMessage: "Welcome to the Jenkins Instance."
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          name: Admin
          password: ${USER_ADMIN_PASSWORD}
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Admin"
            permissions:
              - "Overall/Administer"
            entries:
              - user: "admin"

jobs:
  - file: /var/jenkins_home/casc_configs/job_dsl.groovy